NAME	= libft.a

CC		= cc
CFLAG	= -Wall -Wextra -Werror -g

RM		= rm -f

SRC_1	= ft_isalpha.c \
	ft_isdigit.c \
	ft_isalnum.c \
	ft_isascii.c \
	ft_isprint.c \
	ft_strlen.c \
	ft_memset.c \
	ft_bzero.c \
	ft_memcpy.c \
	ft_memmove.c \
	ft_strlcpy.c \
	ft_strlcat.c \
	ft_toupper.c \
	ft_tolower.c \
	ft_strchr.c \
	ft_strrchr.c \
	ft_strncmp.c \
	ft_memchr.c \
	ft_memcmp.c \
	ft_strnstr.c \
	ft_atoi.c \
	ft_calloc.c \
	ft_strdup.c \

SRC_2	= ft_substr.c \
	ft_strjoin.c \
	ft_strtrim.c \
	ft_split.c \
	ft_itoa.c \
	ft_strmapi.c \
	ft_striteri.c \
	ft_putchar_fd.c \
	ft_putstr_fd.c \
	ft_putendl_fd.c \
	ft_putnbr_fd.c \
	ft_lstmap.c \
	ft_lstiter.c \
	ft_lstclear.c \
	ft_lstdelone.c \
	ft_lstadd_back.c \
	ft_lstlast.c \
	ft_lstsize.c \
	ft_lstadd_front.c \
	ft_lstnew.c \

SRCS	=	$(SRC_1) \
			$(SRC_2) \

OBJS	=	$(SRCS:.c=.o)

OBJECTS = $(OBJS)

all	:	$(NAME)

%.o		: %.c
		$(CC) $(CFLAG) -c $< -o $@


clean	:
		$(RM) $(OBJECTS)

fclean	: clean
		$(RM) $(NAME)

re	: fclean all

$(NAME)	: $(OBJECTS)
		ar -cr $@ $^

.PHONY	: all clean fclean